feat: division into 2 service, add docker
hedonist88/java-shareit pull request #6
Opened 2022-10-05 00:22 UTC by hedonist88

2022-10-05 00:38 UTC, hedonist88 commented
В постмане у меня все чистенько
https://github.com/hedonist88/java-shareit/pull/6

2022-10-05 20:05 UTC, Frilock requested changes
Добрый вечер. По работ: не проходят тесты сборки, предлагаю разобраться в чем причина, скорее всего они падают не просто так. Второй момент, вообще в задаче просят, чтобы вы полностью отказались от валидации в основном модуле, поэтому необходимо как минимум убрать из того пом файла зависимость валидации, а дальше уже смотреть. Кроме того, как вариант предлагаю реорганизовать процесс добавления зависимостей в модули.

2022-10-05 20:05 UTC, Frilock commented on shareit-server/pom.xml
> +			<version>2.7.2</version>
Версии библиотек правильнее указывать в одном месте, а именно, в properties, чтобы при смене версии не приходилось лазить по иногда большому pom файлу.

2022-10-05 20:05 UTC, Frilock commented on shareit-server/pom.xml
> +			<version>0.8.8</version>
Вообще библиотеки правильнее подключать в корневом pom файле, чтобы точка добавления зависимостей в проект была в одном месте. Там нужно создать блок dependencyManager и там их добавлять (указывая версии), а тут будет достаточно их объявить (версию указывать не нужно)

2022-10-05 20:05 UTC, Frilock commented on shareit-server/pom.xml
> +		<dependency>
По моему по заданию основная идея в том, чтобы отказаться от валидации в данном модуле вообще. По этому считаю, что нужно убрать зависимость и смотреть дальше

2022-10-06 20:01 UTC, hedonist88 commented
Проблема в тестах тут была из-за указанной временной зоне в докерфайле
Мне кажется тут 2 модуля и поэтому у каждого свои зависимости
Без тестов тут точно не запускается
А валидаю я из контроллеров сервера убрал

2022-10-07 09:54 UTC, Frilock commented on docker-compose.yaml
> +version: '3.8'
Ну вот, прошли =)

2022-10-07 09:57 UTC, Frilock requested changes
Добрый день, по моему Вы так и не убрали зависимость <artifactId>spring-boot-starter-validation</artifactId> по моему комментарию из shareit-server. Если есть какие то проблемы или недопонимание, напиши в Slack.

2022-10-07 13:04 UTC, hedonist88 commented
> Добрый день, по моему Вы так и не убрали зависимость spring-boot-starter-validation по моему комментарию из shareit-server. Если есть какие то проблемы или недопонимание, напиши в Slack.

Да, пардон, не верно понял, тут просто выше указали на зависимоть spring-boot-starter-test, что смутило
Валидацию убрал, классы почистил

2022-10-07 19:28 UTC, Frilock approved these changes
Принято, успехов в дипломной работе.

2022-10-09 20:24 UTC, merged